export const mockUsers = [
  {
    id: "user-1",
    name: "Arya Wijaya",
    email: "arya@example.com",
    school: "University of Lagos",
    department: "Computer Science",
    level: "300",
    role: "buyer",
    created_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "user-2",
    name: "Sarah Johnson",
    email: "sarah@example.com",
    school: "Covenant University",
    department: "Engineering",
    level: "400",
    role: "uploader",
    created_at: "2024-01-10T10:00:00Z",
  },
  {
    id: "user-3",
    name: "David Chen",
    email: "david@example.com",
    school: "University of Ibadan",
    department: "Medicine",
    level: "500",
    role: "uploader",
    created_at: "2024-01-08T10:00:00Z",
  },
]

export const mockResources = [
  {
    id: "resource-1",
    title: "Data Structures and Algorithms Complete Guide",
    description:
      "Comprehensive notes covering all major data structures, algorithms, time complexity analysis with practical examples and coding exercises",
    uploader_id: "user-2",
    department: "Computer Science",
    level: "300",
    price: 2500,
    tags: ["algorithms", "data-structures", "programming", "coding"],
    storage_path: "resources/dsa-notes.pdf",
    file_type: "application/pdf",
    created_at: "2024-01-20T10:00:00Z",
    featured: true,
  },
  {
    id: "resource-2",
    title: "Calculus Past Questions 2020-2023",
    description: "Collection of past examination questions with detailed step-by-step solutions and explanations",
    uploader_id: "user-2",
    department: "Engineering",
    level: "200",
    price: 0,
    tags: ["calculus", "mathematics", "past-questions", "solutions"],
    storage_path: "resources/calculus-pq.pdf",
    file_type: "application/pdf",
    created_at: "2024-01-18T10:00:00Z",
    featured: false,
  },
  {
    id: "resource-3",
    title: "Database Management Systems Masterclass",
    description:
      "Complete course material for DBMS including SQL tutorials, normalization, ER diagrams, and practical projects",
    uploader_id: "user-2",
    department: "Computer Science",
    level: "300",
    price: 3000,
    tags: ["database", "sql", "dbms", "normalization"],
    storage_path: "resources/dbms-notes.pdf",
    file_type: "application/pdf",
    created_at: "2024-01-16T10:00:00Z",
    featured: true,
  },
  {
    id: "resource-4",
    title: "Physics Laboratory Manual & Experiments",
    description:
      "Complete laboratory experiments, procedures, safety guidelines and report templates for Physics students",
    uploader_id: "user-3",
    department: "Engineering",
    level: "100",
    price: 1500,
    tags: ["physics", "laboratory", "experiments", "reports"],
    storage_path: "resources/physics-lab.pdf",
    file_type: "application/pdf",
    created_at: "2024-01-14T10:00:00Z",
    featured: false,
  },
  {
    id: "resource-5",
    title: "Modern Web Development Bootcamp 2024",
    description: "Complete guide to modern web development with React, Node.js, MongoDB, and deployment strategies",
    uploader_id: "user-2",
    department: "Computer Science",
    level: "400",
    price: 5000,
    tags: ["web-development", "react", "nodejs", "fullstack"],
    storage_path: "resources/web-dev.pdf",
    file_type: "application/pdf",
    created_at: "2024-01-12T10:00:00Z",
    featured: true,
  },
  {
    id: "resource-6",
    title: "Organic Chemistry Reactions Summary",
    description: "Quick reference guide for organic chemistry reactions, mechanisms, and synthesis pathways",
    uploader_id: "user-3",
    department: "Medicine",
    level: "200",
    price: 0,
    tags: ["chemistry", "organic", "reactions", "mechanisms"],
    storage_path: "resources/organic-chem.pdf",
    file_type: "application/pdf",
    created_at: "2024-01-10T10:00:00Z",
    featured: false,
  },
  {
    id: "resource-7",
    title: "Machine Learning Fundamentals",
    description: "Introduction to ML algorithms, Python implementation, and real-world applications with datasets",
    uploader_id: "user-2",
    department: "Computer Science",
    level: "400",
    price: 4500,
    tags: ["machine-learning", "python", "ai", "algorithms"],
    storage_path: "resources/ml-fundamentals.pdf",
    file_type: "application/pdf",
    created_at: "2024-01-22T10:00:00Z",
    featured: true,
  },
  {
    id: "resource-8",
    title: "Constitutional Law Case Studies",
    description: "Landmark constitutional law cases with detailed analysis and legal precedents",
    uploader_id: "user-3",
    department: "Law",
    level: "300",
    price: 3500,
    tags: ["law", "constitutional", "cases", "legal"],
    storage_path: "resources/constitutional-law.pdf",
    file_type: "application/pdf",
    created_at: "2024-01-21T10:00:00Z",
    featured: false,
  },
  {
    id: "resource-9",
    title: "Financial Accounting Principles",
    description: "Complete guide to financial accounting with practical examples and exercises",
    uploader_id: "user-2",
    department: "Business Administration",
    level: "200",
    price: 2000,
    tags: ["accounting", "finance", "business", "principles"],
    storage_path: "resources/accounting.pdf",
    file_type: "application/pdf",
    created_at: "2024-01-19T10:00:00Z",
    featured: false,
  },
  {
    id: "resource-10",
    title: "Human Anatomy Atlas",
    description: "Detailed anatomical diagrams and explanations for medical students",
    uploader_id: "user-3",
    department: "Medicine",
    level: "100",
    price: 0,
    tags: ["anatomy", "medical", "diagrams", "human-body"],
    storage_path: "resources/anatomy-atlas.pdf",
    file_type: "application/pdf",
    created_at: "2024-01-17T10:00:00Z",
    featured: true,
  },
]

export const mockTransactions = [
  {
    id: "trans-1",
    buyer_id: "user-1",
    resource_id: "resource-1",
    amount: 2500,
    timestamp: "2024-01-21T10:00:00Z",
  },
  {
    id: "trans-2",
    buyer_id: "user-1",
    resource_id: "resource-3",
    amount: 3000,
    timestamp: "2024-01-19T10:00:00Z",
  },
  {
    id: "trans-3",
    buyer_id: "user-1",
    resource_id: "resource-7",
    amount: 4500,
    timestamp: "2024-01-23T10:00:00Z",
  },
  {
    id: "trans-4",
    buyer_id: "user-1",
    resource_id: "resource-9",
    amount: 2000,
    timestamp: "2024-01-20T10:00:00Z",
  },
]

export const mockWallets = [
  {
    user_id: "user-1",
    balance: 25000,
  },
  {
    user_id: "user-2",
    balance: 45000,
  },
  {
    user_id: "user-3",
    balance: 32000,
  },
]

export const mockSuggestions = [
  "Data Structures",
  "Past Questions",
  "Machine Learning",
  "Web Development",
  "Database Systems",
  "Calculus",
  "Physics Lab",
  "Organic Chemistry",
  "Constitutional Law",
  "Financial Accounting",
]

export const searchPlaceholders = [
  "Search notes...",
  "Find past questions...",
  "Discover resources...",
  "Explore materials...",
  "Search courses...",
]

// Mock current user
export const mockCurrentUser = {
  id: "user-1",
  email: "arya@example.com",
  created_at: "2024-01-15T10:00:00Z",
}
